version: "3.7"

services:
    database_merlin:
        image: postgres
        container_name: database_merlin
        ports:
            - ${DB_LOCAL_PORT}:${DB_PORT}
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./database_data:/data/postgres
        networks:
            backend:
                ipv4_address: ${IPV4_DB}
    app:
        build: .
        container_name: merlin-api
        restart: always
        ports:
            - ${APP_PORT}:${APP_PORT}
        extra_hosts:
            - localhost:192.168.1.202
        volumes:
            - .:/usr/app
        links:
            - database_merlin
        depends_on:
            - database_merlin
        networks:
            backend:
                ipv4_address: ${IPV4_APP}

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16
